I love playing go gusher <3

In [3]:
import cv2

img = cv2.imread("photo.jpg")
cv2.imshow('Employee Photo', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[ WARN:0@112.037] global loadsave.cpp:241 findDecoder imread_('photo.jpg'): can't open/read file: check file path/integrity


error: OpenCV(4.10.0) /Users/xperience/GHA-Actions-OpenCV/_work/opencv-python/opencv-python/opencv/modules/highgui/src/window.cpp:973: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'


In [1]:
import cv2
import dlib
from deepface import DeepFace
import pandas as pd

# Initialize dlib's face detector
detector = dlib.get_frontal_face_detector()

# Initialize webcam
cap = cv2.VideoCapture(1)

while True:
    # Capture frame-by-frame
    ret, frame = cap.read()

    if not ret:
        print("Failed to grab frame")
        break

    # Detect faces using dlib
    faces = detector(frame)

    for face in faces:
        # Get the coordinates of the face
        x1, y1, x2, y2 = face.left(), face.top(), face.right(), face.bottom()

        # Crop the face region
        face_crop = frame[y1:y2, x1:x2]

        try:
            # Perform face recognition using DeepFace
            result = DeepFace.find(face_crop, db_path="/Users/komangandikawirasantosa/Face-Rec/DeepFace-IPYNB/Database",
                                   detector_backend="dlib",model_name="Facenet512")

            # Draw a rectangle around the face
            cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)

            # Check if the result is not empty
            if isinstance(result, pd.DataFrame) and not result.empty:
                # Extract the person's name from the first row of the DataFrame
                person_name = result.iloc[0]["identity"].split('/')[-2]  # Extract person name from path
                cv2.putText(frame, person_name, (x1, y1-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 0, 0), 2)
            else:
                print("No match found.")

        except Exception as e:
            print(f"Error during face recognition: {str(e)}")

    # Display the resulting frame
    cv2.imshow('Face Detection and Recognition', frame)

    # Break the loop on 'q' key press
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything is done, release the capture
cap.release()
cv2.destroyAllWindows()


24-10-21 16:52:30 - Searching [[[ 40  34  32]
  [ 46  40  38]
  [ 50  44  42]
  ...
  [ 76  87  99]
  [ 80  94 111]
  [ 83 100 118]]

 [[ 41  35  33]
  [ 44  38  36]
  [ 46  40  38]
  ...
  [ 74  86  98]
  [ 78  93 110]
  [ 84 100 121]]

 [[ 41  35  33]
  [ 49  43  41]
  [ 53  47  45]
  ...
  [ 78  86  99]
  [ 80  92 111]
  [ 84 100 121]]

 ...

 [[ 79 100 118]
  [ 82 101 119]
  [ 81 100 118]
  ...
  [108 140 171]
  [125 156 187]
  [127 161 192]]

 [[ 81  97 118]
  [ 75  91 112]
  [ 80  93 114]
  ...
  [111 142 173]
  [122 154 185]
  [126 160 191]]

 [[ 71  89 110]
  [ 73  89 110]
  [ 82  98 119]
  ...
  [111 142 173]
  [122 154 185]
  [126 160 191]]] in 4 length datastore
24-10-21 16:52:32 - find function duration 2.365701198577881 seconds
No match found.
24-10-21 16:52:33 - Searching [[[ 92 121 152]
  [ 95 122 153]
  [ 97 125 154]
  ...
  [ 48  38  32]
  [ 46  37  31]
  [ 42  32  26]]

 [[ 92 119 150]
  [ 90 118 147]
  [ 92 119 148]
  ...
  [ 44  34  28]
  [ 39  30  24]
  [ 41  31  2

KeyboardInterrupt: 

In [4]:
import pandas as pd

# Set Pandas to display the full content without truncation
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)


In [15]:
from deepface import DeepFace
result = DeepFace.find(img_path="/Users/komangandikawirasantosa/Face-Rec/DeepFace-IPYNB/Database/Andika/Andi2.jpg", db_path="/Users/komangandikawirasantosa/Face-Rec/DeepFace-IPYNB/Database",
                       detector_backend="dlib",model_name="Facenet512", threshold=0.5)
result

24-10-21 16:28:25 - Searching /Users/komangandikawirasantosa/Face-Rec/DeepFace-IPYNB/Database/Andika/Andi2.jpg in 4 length datastore
24-10-21 16:28:42 - find function duration 17.575385808944702 seconds


[                                                                           identity  \
 0  /Users/komangandikawirasantosa/Face-Rec/DeepFace-IPYNB/Database/Andika/Andi2.JPG   
 
                                        hash  target_x  target_y  target_w  \
 0  d3f2486ff2fdca39de5bce7feca5181337021e12        37      1812      1656   
 
    target_h  source_x  source_y  source_w  source_h  threshold  distance  
 0      1657        37      1812      1656      1657        0.5       0.0  ]

In [ ]:
from deepface import DeepFace
import matplotlib.pyplot as plt
import numpy as np
import cv2

# List of available backends, models, and distance metrics
backends = ["opencv", "ssd", "dlib", "mtcnn", "retinaface"]
models = ["VGG-Face", "Facenet", "Facenet512", "OpenFace", "DeepFace", "DeepID", "ArcFace", "Dlib", "SFace"]
metrics = ["cosine", "euclidean", "euclidean_l2"]

img = "images/patricia.jpg"

def face_recognition(img):
    # Perform face recognition on the provided image
    people = DeepFace.find(img_path=img, db_path="images/", model_name=models[0], distance_metric=metrics[1])

    # Display the original image
    plt.imshow(cv2.imread(img))
    plt.axis('off')  # Hide axes
    plt.show()

    # Print the identities of the recognized people
    for person in people:
        identity = person.get('identity', ['Unknown'])[0]
        name = identity.split('/')[-1].split('.')[0]  # Extract name without extension
        print(name)

def realtime_face_recognition():
    # Define a video capture object
    vid = cv2.VideoCapture(1)

    while True:
        # Capture the video frame by frame
        ret, frame = vid.read()
        if not ret:
            print("Failed to capture video frame.")
            break

        # Perform face recognition on the captured frame
        try:
            people = DeepFace.find(img_path=frame, db_path="/Users/komangandikawirasantosa/Face-Rec/DeepFace-IPYNB/Database", model_name=models[0], distance_metric=metrics[2], enforce_detection=False)
        except Exception as e:
            print(f"Error during face recognition: {e}")
            continue

        # Check if the people list is empty
        if not people:
            cv2.putText(frame, "Unknown", (50, 50), cv2.FONT_ITALIC, 2, (0, 0, 255), 2)
        else:
            for person in people:
                # Ensure required keys are in the person dictionary
                if all(key in person for key in ['source_x', 'source_y', 'source_w', 'source_h']):
                    # Retrieve the coordinates of the face bounding box safely
                    x = person['source_x'][0] if len(person['source_x']) > 0 else 0
                    y = person['source_y'][0] if len(person['source_y']) > 0 else 0
                    w = person['source_w'][0] if len(person['source_w']) > 0 else 0
                    h = person['source_h'][0] if len(person['source_h']) > 0 else 0

                    # Draw a rectangle around the face
                    cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)

                    # Get the person's name and display it on the image
                    if 'identity' in person and len(person['identity']) > 0:
                        identity = person['identity'][0].split('/')[-1].split('.')[0]  # Extract name without extension
                        cv2.putText(frame, identity, (x, y), cv2.FONT_ITALIC, 1, (0, 0, 255), 2)
                    else:
                        cv2.putText(frame, "Unknown", (x, y), cv2.FONT_ITALIC, 1, (0, 0, 255), 2)

        # Display the resulting frame
        cv2.namedWindow('frame', cv2.WINDOW_NORMAL)
        cv2.resizeWindow('frame', 960, 720)
        cv2.imshow('frame', frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    vid.release()
    cv2.destroyAllWindows()

# Perform face recognition on a single image
# face_recognition(img)

# Perform real-time face recognition using the webcam
realtime_face_recognition()

24-10-21 17:25:58 - Searching [[[40 44 46]
  [40 44 46]
  [41 45 47]
  ...
  [65 65 65]
  [65 65 65]
  [65 65 65]]

 [[40 44 46]
  [40 44 46]
  [40 44 46]
  ...
  [65 65 65]
  [65 65 65]
  [64 64 64]]

 [[40 44 46]
  [40 44 46]
  [40 44 46]
  ...
  [65 65 65]
  [64 64 64]
  [64 64 64]]

 ...

 [[52 70 80]
  [52 70 80]
  [52 70 80]
  ...
  [ 6 10 12]
  [ 6 10 12]
  [ 6 10 12]]

 [[52 70 80]
  [52 70 80]
  [52 70 80]
  ...
  [ 6 10 12]
  [ 6 10 12]
  [ 6 10 12]]

 [[52 70 80]
  [52 70 80]
  [52 70 80]
  ...
  [ 6 10 12]
  [ 6 10 12]
  [ 6 10 12]]] in 4 length datastore
24-10-21 17:26:01 - find function duration 2.5724730491638184 seconds
24-10-21 17:26:01 - Searching [[[53 59 63]
  [54 60 64]
  [53 59 63]
  ...
  [ 2  1 35]
  [ 0  0 34]
  [ 0  0 34]]

 [[53 59 63]
  [53 59 63]
  [53 59 63]
  ...
  [ 2  1 35]
  [ 2  1 35]
  [ 2  1 35]]

 [[52 58 62]
  [53 59 63]
  [53 59 63]
  ...
  [ 0  0 35]
  [ 2  0 36]
  [ 2  0 36]]

 ...

 [[29 24 18]
  [29 24 18]
  [28 23 17]
  ...
  [97 99 99]
  [9

24-10-21 17:27:23 - find function duration 0.9180769920349121 seconds


KeyboardInterrupt: 

In [1]:
import time
from deepface import DeepFace
import cv2

# Optimized variables
backends = ["mtcnn", "retinaface"]  # Faster backends
models = ["Facenet", "ArcFace"]     # Efficient models for faster recognition
metrics = ["cosine", "euclidean"]   # Metrics for distance calculation
frame_count = 0
process_every_n_frame = 5  # Process every 5th frame for speed

def realtime_face_recognition():
    # Define a video capture object
    vid = cv2.VideoCapture(0)

    while True:
        ret, frame = vid.read()
        if not ret:
            print("Failed to capture video frame.")
            break

        # Process only every nth frame to reduce load
        global frame_count
        frame_count += 1
        if frame_count % process_every_n_frame != 0:
            continue

        # Resize frame to speed up recognition
        resized_frame = cv2.resize(frame, (640, 480))  # Reduce resolution for faster processing

        # Perform face recognition on the captured frame
        try:
            start_time = time.time()
            people = DeepFace.find(img_path=resized_frame, 
                                   db_path="/Users/komangandikawirasantosa/Face-Rec/DeepFace-IPYNB/Database", 
                                   model_name=models[0], 
                                   distance_metric=metrics[1], 
                                   enforce_detection=False)
            end_time = time.time()
            print(f"Recognition took {end_time - start_time:.2f} seconds")
        except Exception as e:
            print(f"Error during face recognition: {e}")
            continue

        # Check if the people list is empty
        if not people:
            cv2.putText(frame, "Unknown", (50, 50), cv2.FONT_ITALIC, 2, (0, 0, 255), 2)
        else:
            for person in people:
                if all(key in person for key in ['source_x', 'source_y', 'source_w', 'source_h']):
                    # Retrieve the coordinates of the face bounding box safely
                    x = person['source_x'][0] if len(person['source_x']) > 0 else 0
                    y = person['source_y'][0] if len(person['source_y']) > 0 else 0
                    w = person['source_w'][0] if len(person['source_w']) > 0 else 0
                    h = person['source_h'][0] if len(person['source_h']) > 0 else 0

                    # Draw a rectangle around the face
                    cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)

                    # Get the person's name and display it on the image
                    if 'identity' in person and len(person['identity']) > 0:
                        identity = person['identity'][0].split('/')[-1].split('.')[0]  # Extract name without extension
                        cv2.putText(frame, identity, (x, y), cv2.FONT_ITALIC, 1, (0, 0, 255), 2)
                    else:
                        cv2.putText(frame, "Unknown", (x, y), cv2.FONT_ITALIC, 1, (0, 0, 255), 2)

        # Display the resulting frame
        cv2.namedWindow('frame', cv2.WINDOW_NORMAL)
        cv2.resizeWindow('frame', 960, 720)
        cv2.imshow('frame', frame)

        # Break loop on 'q' press
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    # Release the video capture object and close windows
    vid.release()
    cv2.destroyAllWindows()

# Start real-time face recognition
realtime_face_recognition()


24-10-22 11:05:26 - Found 4 newly added image(s), 0 removed image(s), 0 replaced image(s).


Finding representations:   0%|                            | 0/4 [00:00<?, ?it/s]

24-10-22 11:05:28 - facenet_weights.h5 will be downloaded...


Downloading...
From: https://github.com/serengil/deepface_models/releases/download/v1.0/facenet_weights.h5
To: /Users/komangandikawirasantosa/.deepface/weights/facenet_weights.h5
100%|██████████████████████████████████████| 92.2M/92.2M [01:02<00:00, 1.47MB/s]
Finding representations: 100%|████████████████████| 4/4 [01:16<00:00, 19.17s/it]


24-10-22 11:06:43 - There are now 4 representations in ds_model_facenet_detector_opencv_aligned_normalization_base_expand_0.pkl
24-10-22 11:06:43 - Searching [[[  7  12  13]
  [  7  11  13]
  [  6  10  12]
  ...
  [119  99  96]
  [119  99  96]
  [120 101  98]]

 [[  7  12  13]
  [  8  13  14]
  [  7  12  13]
  ...
  [119  99  96]
  [119  99  96]
  [119  99  96]]

 [[  7  12  13]
  [  6  10  12]
  [  7  12  13]
  ...
  [119  99  96]
  [119  99  96]
  [119  99  96]]

 ...

 [[110 146 167]
  [110 146 167]
  [110 145 169]
  ...
  [ 66  63  60]
  [ 78  76  71]
  [ 92  92  89]]

 [[111 147 168]
  [112 148 170]
  [110 146 167]
  ...
  [ 56  53  49]
  [ 61  57  55]
  [ 73  69  67]]

 [[113 149 171]
  [114 151 172]
  [112 148 170]
  ...
  [ 56  53  49]
  [ 55  51  49]
  [ 58  54  52]]] in 4 length datastore
24-10-22 11:06:43 - find function duration 76.97061491012573 seconds
Recognition took 76.97 seconds
24-10-22 11:06:43 - Searching [[[171 172 167]
  [171 172 167]
  [171 172 167]
  ...
  [119